// <auto-generated />
namespace Family.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTableIncome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTableIncome));
        
        string IMigrationMetadata.Id
        {
            get { return "202102171018596_NewTable-Income"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
